services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=task_management'
      - 'POSTGRES_PASSWORD=youssefGamal'
      - 'POSTGRES_USER=1234'
    ports:
      - '5432:5432'
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
